Update ncepvpn
Check for openconnect in initUser function.

diff --git a/src/ncepvpn b/src/ncepvpn
--- a/src/ncepvpn
+++ b/src/ncepvpn
@@ -26,8 +26,9 @@ trap 'stty sane; exit' SIGINT SIGQUIT
 # ---------------------------------------------------------------------------------------- 
 # Define process ID file
 # ---------------------------------------------------------------------------------------- 
-PIDFILE=/var/run/openconnect.pid
 NCEPVPN_VERSION="1.1.0-beta"
+OPENCONNECT=/usr/sbin/openconnect
+PIDFILE=/var/run/openconnect.pid
 
 # ---------------------------------------------------------------------------------------- 
 # Function: connect - wrapper for openconnect. 
@@ -36,7 +37,7 @@ connect()
 {
    # Check if the PIDFILE does not exist, then start openconnect
    if [ ! -f $PIDFILE ]; then
-      /usr/sbin/openconnect -u $NCEPUSER --config=$OPENCONNECT_CONFIG --background \
+      $OPENCONNECT -u $NCEPUSER --config=$OPENCONNECT_CONFIG --background \
                             --pid-file=$PIDFILE $NCEPHOST
    else
       echo -ne "\n You are currently connected to the NCEP VPN \n\n"
@@ -78,6 +79,13 @@ getConfigFiles()
 # ---------------------------------------------------------------------------------------- 
 initUser()
 {
+
+   # Check for openconnect
+   if [ ! -x $OPENCONNECT ]; then
+      echo "$(basename $0): openconnect not found"
+      exit 1
+   fi
+   
    # Get the config file names
    getConfigFiles
    
